# Generated by Django 4.2.25 on 2025-11-18 07:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_contactmessage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="impact_summary",
        ),
        migrations.AddField(
            model_name="project",
            name="impact",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                default=list,
                help_text="Enter a list of impact points. Each entry can be long or short.",
                size=None,
            ),
        ),
    ]
