# Generated by Django 4.2.25 on 2025-12-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_project_impact_summary_project_impact"),
    ]

    operations = [
        migrations.AddField(
            model_name="pillar",
            name="activities",
            field=models.JSONField(
                default=list,
                help_text="A list of activities displayed on detailed page & home page",
            ),
        ),
        migrations.AddField(
            model_name="pillar",
            name="short_description",
            field=models.TextField(
                blank=True, help_text="Optional shorter version for home page"
            ),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="image",
            field=models.ImageField(upload_to="media/gallery/"),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="photo",
            field=models.ImageField(blank=True, upload_to="media/team/"),
        ),
    ]
