# Generated by Django 4.2.25 on 2025-12-16 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_pillar_activities_pillar_short_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="related_pillar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gallery_images",
                to="core.pillar",
            ),
        ),
    ]
