# Generated by Django 4.2.25 on 2025-12-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_gallery_related_pillar"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="short_description",
            field=models.TextField(
                blank=True, help_text="A short summary for list views."
            ),
        ),
    ]
