# Generated by Django 4.2.25 on 2025-12-17 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_project_short_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="media/hero/")),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.DeleteModel(
            name="SiteSetting",
        ),
        migrations.AddField(
            model_name="organizationinfo",
            name="about_background",
            field=models.TextField(blank=True, help_text="Our Background content"),
        ),
        migrations.AddField(
            model_name="organizationinfo",
            name="account_no",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="organizationinfo",
            name="core_values",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="organizationinfo",
            name="footer_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="organizationinfo",
            name="hero_subtitle",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="organizationinfo",
            name="hero_title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="organizationinfo",
            name="meta_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="organizationinfo",
            name="meta_keywords",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="organizationinfo",
            name="paybill_no",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="heroimage",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hero_images",
                to="core.organizationinfo",
            ),
        ),
    ]
